#!/usr/bin/env bash

case "$(printf "kill\nreboot\nshutdown" | dmenu -i -l 4)" in
	kill) ps -u $USER -o pid,comm,%cpu,%mem | dmenu -i -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	reboot) systemctl reboot -i ;;
	shutdown) shutdown now ;;
	*) exit 1 ;;
esac
